# Generated by Django 2.2.28 on 2023-08-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wef', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GGH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdf', models.CharField(max_length=250)),
                ('asaf', models.BigIntegerField(blank=True, null=True)),
                ('rel_ggh_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ggh_rel_ggh_1_1', to='home.GGH')),
                ('rel_user_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ggh_rel_user_1_1', to=settings.AUTH_USER_MODEL)),
                ('rel_user_1_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ggh_rel_user_1_n', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
