# Generated by Django 2.2.28 on 2023-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bbn_ggh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbn',
            name='wef',
        ),
        migrations.AddField(
            model_name='bbn',
            name='wejjk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
